#!/usr/bin/env bb
;; swarm_handoff.bb — the strict outbound protocol gate.
;;
;; Validates an agent-written draft, generates the canonical handoff, and
;; atomically installs it into this worktree's outbox for the router daemon.
;; Error output is written for agents: every problem, with repair guidance.

(load-file (str (babashka.fs/path (babashka.fs/parent *file*) "handoff_lib.bb")))

(ns swarm-handoff
  (:require [babashka.fs :as fs]
            [babashka.process :as process]
            [clojure.string :as str]))

(def usage-text
  (str "Usage: swarm_handoff.sh <draft-file>\n\n"
       "Draft formats:\n\n"
       "type: git_handoff\n"
       "to: <role>[,<role>...]\n"
       "priority: NN\n"
       "task: <short-stable-task-name>\n"
       "commit: <10-char-commit-abbrev>\n\n"
       "type: note\n"
       "to: <role>[,<role>...]\n"
       "priority: NN\n"
       "message: <one line, max 80 chars>"))

(def reserved-headers
  #{"id" "from" "role" "recipient" "created_at" "enqueued_at" "dequeued_at" "completed_at"})

(def draft-headers #{"type" "to" "priority" "task" "commit" "message"})

(def headers-by-type
  {"git_handoff" #{"type" "to" "priority" "task" "commit"}
   "note" #{"type" "to" "priority" "message"}})

;; --- draft parsing --------------------------------------------------------

(defn parse-draft
  "Header lines, optional blank line; anything after the blank line is an
  error (payloads are generated, never written by agents)."
  [draft]
  (reduce
   (fn [{:keys [in-body?] :as acc} [line-no line]]
     (cond
       in-body?
       (cond-> acc
         (not (str/blank? line))
         (update :errors conj
                 (format "Line %d: draft handoffs may contain headers only; payloads are generated by swarm_handoff.sh." line-no)))

       (str/blank? line)
       (assoc acc :in-body? true)

       :else
       (let [[field value] (str/split line #": " 2)]
         (cond
           (or (nil? value) (str/blank? field) (str/blank? value))
           (update acc :errors conj
                   (if (str/includes? line ": ")
                     (format "Line %d: field and value must both be non-empty." line-no)
                     (format "Line %d: expected 'field: value'." line-no)))

           (reserved-headers field)
           (update acc :errors conj
                   (format "Line %d: header '%s' is reserved and must not be written by agents." line-no field))

           (not (draft-headers field))
           (update acc :errors conj (format "Line %d: unknown header '%s'." line-no field))

           (contains? (:headers acc) field)
           (update acc :errors conj (format "Line %d: duplicate header '%s'." line-no field))

           :else
           (update acc :headers assoc field value)))))
   {:headers {} :errors [] :in-body? false}
   (map-indexed (fn [i line] [(inc i) line])
                (str/split-lines (slurp (str draft))))))

;; --- validation -----------------------------------------------------------

(defn recipient-errors [recipients]
  (second
   (reduce (fn [[seen errors] recipient]
             [(conj seen recipient)
              (cond-> errors
                (str/blank? recipient)
                (conj "Header 'to' contains an empty recipient.")
                (str/includes? recipient "_")
                (conj (format "Recipient role '%s' is invalid; role names may not contain underscores." recipient))
                (contains? seen recipient)
                (conj (format "Duplicate recipient '%s'." recipient))
                (and (not (str/blank? recipient))
                     (not (handoff-lib/role-known? recipient)))
                (conj (format "Unknown recipient role '%s'." recipient)))])
           [#{} []]
           recipients)))

(defn canonical-commit
  "Resolve a 10-hex-char abbreviation to exactly one commit; return
  [canonical-abbrev error]."
  [commit]
  (let [{:keys [out]} (process/sh {:continue true}
                                  "git" "rev-parse" (str "--disambiguate=" commit))
        matches (vec (remove str/blank? (str/split-lines out)))]
    (if (not= 1 (count matches))
      [nil (format "Header 'commit' must resolve to exactly one Git object; '%s' matched %d." commit (count matches))]
      (let [object (first matches)
            object-type (str/trim (:out (process/sh {:continue true} "git" "cat-file" "-t" object)))]
        (if (= "commit" object-type)
          [(str/trim (:out (process/sh "git" "rev-parse" "--short=10" object))) nil]
          [nil (format "Header 'commit' must resolve to a commit; '%s' resolves to '%s'." commit object-type)])))))

(defn validate [headers]
  (let [{:strs [type to priority task commit message]} headers
        recipients (when-not (str/blank? to) (str/split to #"," -1))
        allowed (get headers-by-type type)
        structural
        (cond-> []
          (str/blank? type) (conj "Missing required header 'type'.")
          (str/blank? to) (conj "Missing required header 'to'.")
          (str/blank? priority) (conj "Missing required header 'priority'.")
          (and type (not (contains? headers-by-type type)))
          (conj (format "Header 'type' must be one of git_handoff or note; got '%s'." type))
          (and priority (not (re-matches #"[0-9][0-9]" priority)))
          (conj (format "Header 'priority' must be two digits from 00 to 99; got '%s'." priority)))
        misplaced (when allowed
                    (for [field (keys headers)
                          :when (not (allowed field))]
                      (format "Header '%s' is not allowed for type '%s'." field type)))
        [canonical commit-errors]
        (if (= "git_handoff" type)
          (cond
            (str/blank? commit)
            [nil ["Missing required header 'commit' for git_handoff."]]
            (not (re-matches #"[0-9a-fA-F]{10}" commit))
            [nil [(format "Header 'commit' must be exactly 10 hexadecimal characters; got '%s'." commit)]]
            :else (update (vec (canonical-commit commit)) 1 #(if % [%] [])))
          [nil []])
        task-errors
        (when (= "git_handoff" type)
          (cond-> []
            (str/blank? task) (conj "Missing required header 'task' for git_handoff.")
            (> (count (or task "")) 80)
            (conj (format "Header 'task' must be no longer than 80 characters; got %d." (count task)))))
        message-errors
        (when (= "note" type)
          (cond-> []
            (str/blank? message) (conj "Missing required header 'message' for note.")
            (> (count (or message "")) 80)
            (conj (format "Header 'message' must be no longer than 80 characters; got %d." (count message)))))]
    {:recipients recipients
     :canonical-commit canonical
     :errors (vec (concat structural
                          (when recipients (recipient-errors recipients))
                          misplaced commit-errors task-errors message-errors))}))

;; --- generation -----------------------------------------------------------

(defn generated-body [type sender canonical-commit message]
  (str "Re-read your role and constitution.\n\n"
       (case type
         "git_handoff" (str "merge_and_process " sender " " canonical-commit)
         "note" message)))

(defn queue! [{:strs [type priority task message]} sender recipients canonical-commit]
  (let [stamp (handoff-lib/compact-now)
        sequence (handoff-lib/next-sequence)
        filename (str priority "_" stamp "_" sequence
                      "_from_" sender "_to_" (str/join "_" recipients) ".handoff")
        outbox (fs/path (handoff-lib/state-dir) "outbox")
        tmp (fs/path outbox "tmp" (str filename ".tmp"))
        final (fs/path outbox filename)
        headers (cond-> {"id" (str stamp "_" sequence "_from_" sender)
                         "from" sender
                         "to" (str/join "," recipients)
                         "priority" priority
                         "type" type
                         "created_at" (handoff-lib/iso-now)}
                  (= type "git_handoff") (assoc "role" sender
                                                "task" task
                                                "commit" canonical-commit)
                  (= type "note") (assoc "message" message))]
    (handoff-lib/ensure-queue-dirs! (handoff-lib/state-dir))
    (spit (str tmp) (str (handoff-lib/render-handoff
                          {:headers headers
                           :body (generated-body type sender canonical-commit message)})
                         "\n"))
    (fs/move tmp final)
    final))

;; --- entry ----------------------------------------------------------------

(defn -main [args]
  (when (not= 1 (count args))
    (binding [*out* *err*] (println usage-text))
    (System/exit 1))
  (let [draft (fs/path (first args))]
    (when-not (fs/regular-file? draft)
      (handoff-lib/die 1 (str "Draft file not found: " draft)))
    (let [sender (handoff-lib/current-role)]
      (when-not (handoff-lib/role-known? sender)
        (handoff-lib/die 1 (str "Unknown sender role: " sender)))
      (let [{:keys [headers errors]} (parse-draft draft)
            validation (validate headers)
            all-errors (into errors (:errors validation))]
        (when (seq all-errors)
          (binding [*out* *err*]
            (println "HANDOFF INVALID:" (str draft))
            (println)
            (println "Errors:")
            (doseq [error all-errors] (println "-" error))
            (println)
            (println usage-text))
          (System/exit 2))
        (let [queued (queue! headers sender
                             (:recipients validation)
                             (:canonical-commit validation))]
          (fs/delete draft)
          (println "HANDOFF QUEUED:" (str queued)))))))

(handoff-lib/run-entry #(-main *command-line-args*))
